jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "Hello world"
  
 
- job: myJob_2
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: echo "Hello worldwindows"